# Generated by Django 5.1.7 on 2025-03-20 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_order_orderitem_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Invalid Name', regex='^[a-zA-Z0-9 ]+$')]),
        ),
    ]
