# Generated by Django 5.1.7 on 2025-03-23 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
